import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { prisma } from '@/lib/prisma'
import { createServerSupabaseClient } from '@/lib/supabase-server'

const stages = ['DETECTED','CONTACTED','REPLIED','MEETING','DEMO','PROPOSAL','NEGOTIATION','WON','LOST'] as const
const profileSchema = z.object({
  leadId: z.string().optional(), companyName: z.string().min(1), contactName: z.string().optional(), instagram: z.string().optional(), whatsapp: z.string().optional(),
  website: z.string().optional(), country: z.string().optional(), industry: z.string().default('Taller automotriz'), stage: z.enum(stages).default('DETECTED'),
  observation: z.string().optional(), pain: z.string().optional(), desiredService: z.string().optional(), currentAcquisition: z.string().optional(),
  decisionMaker: z.boolean().default(false), hasNeed: z.boolean().default(false), hasBudget: z.boolean().default(false), hasUrgency: z.boolean().default(false),
  nextFollowUpAt: z.string().optional(), estimatedValue: z.number().nonnegative().optional(), lastResponse: z.string().optional(),
})

async function userContext(){const supabase=await createServerSupabaseClient();const {data:{session}}=await supabase.auth.getSession();if(!session?.user?.email)return null;return prisma.user.findUnique({where:{email:session.user.email}})}
const profileFrom=(lead:any)=>{const entry=lead.activities?.find((a:any)=>(a.metadata as any)?.kind==='acquisition_profile');return {...((entry?.metadata as any)?.profile??{}),leadId:lead.id,companyName:lead.companyName,contactName:lead.contactName??'',instagram:lead.instagram??'',whatsapp:lead.whatsapp??'',website:lead.website??'',country:lead.country??'',industry:lead.industry??'',stage:lead.stage,estimatedValue:lead.estimatedValue??undefined,nextFollowUpAt:lead.nextFollowUpAt?.toISOString()??''}}

export async function GET(){try{const user=await userContext();if(!user)return NextResponse.json({error:'No autorizado'},{status:401});const leads=await prisma.lead.findMany({where:{workspaceId:user.workspaceId,source:{in:['COLD_OUTREACH','MANUAL']}},include:{activities:{where:{type:'AI_INSIGHT'},orderBy:{createdAt:'desc'},take:10}},orderBy:{updatedAt:'desc'}});return NextResponse.json({data:leads.map(profileFrom)})}catch(e){console.error(e);return NextResponse.json({error:'Error interno'},{status:500})}}

export async function POST(req:NextRequest){try{const user=await userContext();if(!user)return NextResponse.json({error:'No autorizado'},{status:401});const p=profileSchema.parse(await req.json());const lead=await prisma.lead.create({data:{workspaceId:user.workspaceId,assignedToId:user.id,companyName:p.companyName,contactName:p.contactName,instagram:p.instagram,whatsapp:p.whatsapp,website:p.website||undefined,country:p.country,industry:p.industry,source:'COLD_OUTREACH',stage:p.stage,estimatedValue:p.estimatedValue,nextFollowUpAt:p.nextFollowUpAt?new Date(p.nextFollowUpAt):undefined,activities:{create:{type:'AI_INSIGHT',userId:user.id,description:'Ficha de adquisición creada',metadata:{kind:'acquisition_profile',profile:p}}}}});return NextResponse.json({data:{...p,leadId:lead.id}},{status:201})}catch(e){if(e instanceof z.ZodError)return NextResponse.json({error:'Datos inválidos',details:e.errors},{status:400});console.error(e);return NextResponse.json({error:'Error interno'},{status:500})}}

export async function PATCH(req:NextRequest){try{const user=await userContext();if(!user)return NextResponse.json({error:'No autorizado'},{status:401});const p=profileSchema.extend({leadId:z.string()}).parse(await req.json());const exists=await prisma.lead.findFirst({where:{id:p.leadId,workspaceId:user.workspaceId}});if(!exists)return NextResponse.json({error:'Taller no encontrado'},{status:404});await prisma.$transaction([prisma.lead.update({where:{id:p.leadId},data:{companyName:p.companyName,contactName:p.contactName,instagram:p.instagram,whatsapp:p.whatsapp,website:p.website||null,country:p.country,industry:p.industry,stage:p.stage,estimatedValue:p.estimatedValue,nextFollowUpAt:p.nextFollowUpAt?new Date(p.nextFollowUpAt):null,lastContactedAt:['CONTACTED','REPLIED','MEETING','DEMO','PROPOSAL','NEGOTIATION'].includes(p.stage)?new Date():undefined}}),prisma.activity.create({data:{leadId:p.leadId,userId:user.id,type:'AI_INSIGHT',description:`Adquisición actualizada: ${p.stage}`,metadata:{kind:'acquisition_profile',profile:p}}})]);return NextResponse.json({data:p})}catch(e){if(e instanceof z.ZodError)return NextResponse.json({error:'Datos inválidos',details:e.errors},{status:400});console.error(e);return NextResponse.json({error:'Error interno'},{status:500})}}
