'use client'
import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Topbar } from '@/components/layout/Topbar'
import { Modal, Field, Input } from '@/components/ui/Modal'
import { formatCurrency } from '@/lib/utils'

type Stage='DETECTED'|'CONTACTED'|'REPLIED'|'MEETING'|'DEMO'|'PROPOSAL'|'NEGOTIATION'|'WON'|'LOST'
type Profile={leadId?:string;companyName:string;contactName:string;instagram:string;whatsapp:string;website:string;country:string;industry:string;stage:Stage;observation:string;pain:string;desiredService:string;currentAcquisition:string;decisionMaker:boolean;hasNeed:boolean;hasBudget:boolean;hasUrgency:boolean;nextFollowUpAt:string;estimatedValue?:number;lastResponse:string}
type Advice={diagnosis:string;nextStep:string;message:string;questions:string[];score:number;risk:'bajo'|'medio'|'alto';shouldDemo:boolean;rationale:string}
type ChatMessage={id?:string;role:'user'|'assistant';content:string;createdAt?:string}
const STAGES:{id:Stage;label:string;short:string;icon:string}[]=[{id:'DETECTED',label:'Detectado',short:'Investigar',icon:'ti-radar'},{id:'CONTACTED',label:'Contactado',short:'Abrir conversación',icon:'ti-send'},{id:'REPLIED',label:'Respondió',short:'Calificar',icon:'ti-message-circle'},{id:'MEETING',label:'Diagnóstico',short:'Agendar llamada',icon:'ti-phone'},{id:'DEMO',label:'Demo',short:'Mostrar solución',icon:'ti-presentation'},{id:'PROPOSAL',label:'Propuesta',short:'Presentar inversión',icon:'ti-file-dollar'},{id:'NEGOTIATION',label:'Negociación',short:'Resolver objeciones',icon:'ti-scale'},{id:'WON',label:'Ganado',short:'Onboarding',icon:'ti-trophy'},{id:'LOST',label:'Perdido',short:'Registrar motivo',icon:'ti-x'}]
const blank:Profile={companyName:'',contactName:'',instagram:'',whatsapp:'',website:'',country:'',industry:'Taller automotriz',stage:'DETECTED',observation:'',pain:'',desiredService:'',currentAcquisition:'',decisionMaker:false,hasNeed:false,hasBudget:false,hasUrgency:false,nextFollowUpAt:'',lastResponse:''}
async function json(url:string,init?:RequestInit){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...init});const j=await r.json();if(!r.ok)throw new Error(j.error||'Error');return j.data}

export default function AcquisitionPage(){
 const qc=useQueryClient();const [selectedId,setSelectedId]=useState('');const [draft,setDraft]=useState<Profile>(blank);const [createOpen,setCreateOpen]=useState(false);const [advice,setAdvice]=useState<Advice|null>(null);const [copied,setCopied]=useState(false);const [chatMessages,setChatMessages]=useState<ChatMessage[]>([]);const [chatInput,setChatInput]=useState('')
 const {data:profiles=[],isLoading}=useQuery<Profile[]>({queryKey:['acquisition'],queryFn:()=>json('/api/acquisition')})
 const selected=profiles.find(x=>x.leadId===selectedId)||profiles[0]
 useEffect(()=>{if(selected){setSelectedId(selected.leadId!);setDraft({...blank,...selected});setAdvice(null);setChatMessages([]);json(`/api/ai/acquisition-chat?leadId=${selected.leadId}`).then(setChatMessages).catch(()=>setChatMessages([]))}},[selected?.leadId])
 const save=useMutation({mutationFn:(p:Profile)=>json('/api/acquisition',{method:p.leadId?'PATCH':'POST',body:JSON.stringify({...p,estimatedValue:p.estimatedValue?Number(p.estimatedValue):undefined,nextFollowUpAt:p.nextFollowUpAt?new Date(p.nextFollowUpAt).toISOString():undefined})}),onSuccess:(p:Profile)=>{qc.invalidateQueries({queryKey:['acquisition']});setSelectedId(p.leadId!);setCreateOpen(false)}})
 const coach=useMutation({mutationFn:()=>json('/api/ai/acquisition-coach',{method:'POST',body:JSON.stringify({leadId:draft.leadId,profile:draft})}),onSuccess:setAdvice})
 const chat=useMutation({mutationFn:(message:string)=>json('/api/ai/acquisition-chat',{method:'POST',body:JSON.stringify({leadId:draft.leadId,message})}),onMutate:(message)=>{setChatMessages(x=>[...x,{role:'user',content:message}]);setChatInput('')},onSuccess:(reply:ChatMessage)=>setChatMessages(x=>[...x,reply])})
 const stageIndex=STAGES.findIndex(x=>x.id===draft.stage);const qualification=[draft.hasNeed,draft.decisionMaker,draft.hasBudget,draft.hasUrgency].filter(Boolean).length
 const totals=useMemo(()=>({active:profiles.filter(x=>!['WON','LOST'].includes(x.stage)).length,qualified:profiles.filter(x=>[x.hasNeed,x.decisionMaker,x.hasBudget,x.hasUrgency].filter(Boolean).length>=3).length,value:profiles.reduce((s,x)=>s+(x.estimatedValue||0),0),won:profiles.filter(x=>x.stage==='WON').length}),[profiles])
 function set<K extends keyof Profile>(key:K,value:Profile[K]){setDraft(x=>({...x,[key]:value}))}
 function copy(){if(!advice)return;navigator.clipboard.writeText(advice.message);setCopied(true);setTimeout(()=>setCopied(false),1600)}
 function sendChat(message=chatInput){const clean=message.trim();if(!clean||chat.isPending||!draft.leadId)return;chat.mutate(clean)}
 return <><Topbar title="Acquisition OS" subtitle="Sistema de captación y seguimiento" primaryAction={{label:'Agregar taller',onClick:()=>{setDraft(blank);setCreateOpen(true)}}}/><main className="future-canvas flex-1 overflow-y-auto"><div className="mx-auto max-w-[1540px] space-y-5 p-4 pb-16 md:p-7">
  <section className="module-intro"><div><div className="future-status"><span/>Sales operating system</div><h1>De contacto frío a cliente.</h1><p>Cada taller, cada conversación y el próximo paso recomendado en un solo lugar.</p></div><i className="ti ti-route module-orb"/></section>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[totals.active,'Talleres activos','ti-activity-heartbeat','#22d3ee'],[totals.qualified,'Calificados','ti-rosette-discount-check','#a78bfa'],[formatCurrency(totals.value),'Pipeline potencial','ti-wave-sine','#ff7a1a'],[totals.won,'Clientes ganados','ti-trophy','#34d399']].map(([v,l,i,c])=><article key={String(l)} className="future-panel future-kpi"><div className="flex justify-between"><div><p className="future-label">{l}</p><p className="mt-3 font-mono text-2xl font-semibold text-white">{v}</p></div><div className="future-icon" style={{color:String(c),background:`${c}15`}}><i className={`ti ${i}`}/></div></div></article>)}</section>
  <section className="grid min-h-[690px] grid-cols-1 gap-4 xl:grid-cols-[300px_1fr_390px]">
   <aside className="future-panel overflow-hidden"><div className="border-b border-white/[.055] p-5"><p className="future-label">Prospectos</p><h2 className="mt-2 text-base font-semibold text-white">Talleres contactados</h2></div><div className="max-h-[620px] space-y-1 overflow-y-auto p-2">{isLoading&&<p className="p-6 text-center text-xs text-zinc-600">Cargando…</p>}{!isLoading&&!profiles.length&&<button onClick={()=>setCreateOpen(true)} className="w-full rounded-2xl border border-dashed border-white/10 p-8 text-[11px] text-zinc-600">Agregá el primer taller</button>}{profiles.map(p=>{const st=STAGES.find(x=>x.id===p.stage);return <button key={p.leadId} onClick={()=>setSelectedId(p.leadId!)} className={`w-full rounded-2xl border p-3.5 text-left transition ${selected?.leadId===p.leadId?'border-cyan-300/15 bg-cyan-300/[.055]':'border-transparent hover:bg-white/[.035]'}`}><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.05] text-zinc-400"><i className={`ti ${st?.icon}`}/></div><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-medium text-white">{p.companyName}</p><p className="mt-1 truncate text-[9px] text-zinc-600">{st?.label} · {p.country||'Sin ubicación'}</p></div>{p.nextFollowUpAt&&<span className="h-1.5 w-1.5 rounded-full bg-orange-400 shadow-[0_0_8px_#ff7a1a]"/>}</div></button>})}</div></aside>
   {selected?<section className="space-y-4"><article className="future-panel p-5 md:p-7"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><p className="future-label">Expediente comercial</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em] text-white">{draft.companyName}</h2><p className="mt-1 text-[10px] text-zinc-600">{draft.instagram||draft.website||'Sin perfil cargado'}</p></div><button onClick={()=>save.mutate(draft)} disabled={save.isPending} className="rounded-full bg-white px-4 py-2 text-[10px] font-semibold text-black">{save.isPending?'Guardando…':'Guardar cambios'}</button></div><div className="mt-7 flex gap-2 overflow-x-auto pb-2">{STAGES.map((s,i)=><button key={s.id} onClick={()=>set('stage',s.id)} className={`relative min-w-[94px] rounded-2xl border px-3 py-3 text-left ${draft.stage===s.id?'border-cyan-300/20 bg-cyan-300/[.07]':'border-white/[.055] bg-white/[.025]'}`}><i className={`ti ${s.icon} text-sm ${i<=stageIndex?'text-cyan-300':'text-zinc-700'}`}/><p className={`mt-2 text-[9px] ${draft.stage===s.id?'text-white':'text-zinc-600'}`}>{s.label}</p>{i<STAGES.length-1&&<span className="absolute -right-2.5 top-1/2 h-px w-3 bg-white/10"/>}</button>)}</div></article>
    <article className="future-panel p-5 md:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="future-label">Diagnóstico</p><h3 className="mt-2 text-base font-semibold text-white">Contexto del taller</h3></div><span className="rounded-full bg-white/[.04] px-3 py-1 text-[9px] text-zinc-500">Actualizable</span></div><div className="grid gap-4 md:grid-cols-2"><Field label="Observación real de su marca"><textarea value={draft.observation} onChange={e=>set('observation',e.target.value)} rows={3} placeholder="Qué viste en Instagram, Google o su web…" className="w-full"/></Field><Field label="Problema u oportunidad"><textarea value={draft.pain} onChange={e=>set('pain',e.target.value)} rows={3} placeholder="Qué está perdiendo o puede mejorar…" className="w-full"/></Field><Field label="Cómo consigue clientes hoy"><Input value={draft.currentAcquisition} onChange={e=>set('currentAcquisition',e.target.value)} placeholder="Referidos, Instagram, Google…"/></Field><Field label="Servicio que quiere vender más"><Input value={draft.desiredService} onChange={e=>set('desiredService',e.target.value)} placeholder="Chapa y pintura, detailing…"/></Field><Field label="Última respuesta del cliente"><textarea value={draft.lastResponse} onChange={e=>set('lastResponse',e.target.value)} rows={3} placeholder="Pegá el último mensaje recibido…" className="w-full"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Valor estimado USD"><Input type="number" value={draft.estimatedValue??''} onChange={e=>set('estimatedValue',Number(e.target.value))}/></Field><Field label="Próximo seguimiento"><Input type="datetime-local" value={draft.nextFollowUpAt?.slice(0,16)||''} onChange={e=>set('nextFollowUpAt',e.target.value)}/></Field></div></div></article>
    <article className="future-panel p-5 md:p-7"><div className="flex items-center justify-between"><div><p className="future-label">Qualification gate</p><h3 className="mt-2 text-base font-semibold text-white">¿Está listo para una demo?</h3></div><strong className="font-mono text-2xl text-white">{qualification}/4</strong></div><div className="mt-5 grid grid-cols-2 gap-3">{[['hasNeed','Necesidad real','ti-target'],['decisionMaker','Decisor identificado','ti-user-check'],['hasBudget','Presupuesto posible','ti-wallet'],['hasUrgency','Urgencia definida','ti-bolt']] .map(([k,l,i])=><button key={k} onClick={()=>set(k as keyof Profile,!draft[k as keyof Profile] as never)} className={`flex items-center gap-3 rounded-2xl border p-3 text-left ${draft[k as keyof Profile]?'border-emerald-300/15 bg-emerald-300/[.06]':'border-white/[.055] bg-white/[.02]'}`}><i className={`ti ${i} ${draft[k as keyof Profile]?'text-emerald-300':'text-zinc-700'}`}/><span className="text-[10px] text-zinc-400">{l}</span></button>)}</div></article>
   </section>:<div className="future-panel grid place-items-center text-center"><div><i className="ti ti-radar text-4xl text-zinc-700"/><p className="mt-4 text-xs text-zinc-600">Seleccioná o agregá un taller.</p></div></div>}
   <aside className="future-panel relative flex min-h-[690px] flex-col overflow-hidden">
    <div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-violet-500/10 blur-3xl"/>
    <header className="relative border-b border-white/[.055] p-5">
     <div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-[15px] bg-gradient-to-br from-violet-500 to-indigo-600 text-white shadow-lg shadow-violet-900/30"><i className="ti ti-sparkles text-lg"/></div><div><p className="future-label">OpenAI sales brain</p><h2 className="mt-1 text-base font-semibold text-white">Coach comercial</h2></div><span className="ml-auto flex items-center gap-1.5 rounded-full bg-emerald-400/[.07] px-2.5 py-1 text-[8px] font-medium uppercase tracking-wider text-emerald-300"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-300"/>Activo</span></div>
     <p className="mt-4 text-[10px] leading-5 text-zinc-500">Consultame cómo responder, cuándo hacer seguimiento o cómo cerrar este taller. El contexto se conserva automáticamente.</p>
    </header>
    <div className="relative flex-1 space-y-3 overflow-y-auto p-4">
     {!chatMessages.length&&<div className="grid min-h-[250px] place-items-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-violet-400/10 bg-violet-400/[.045]"><i className="ti ti-brain text-2xl text-violet-400"/></div><p className="mt-4 text-xs font-medium text-zinc-300">Tu estratega para {draft.companyName||'este prospecto'}</p><p className="mx-auto mt-2 max-w-[245px] text-[9px] leading-4 text-zinc-600">Pegá la respuesta del taller o preguntame cuál debería ser tu próximo movimiento.</p></div></div>}
     {chatMessages.map((m,i)=><div key={m.id||i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[90%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-[10px] leading-[1.7] ${m.role==='user'?'rounded-br-md bg-violet-600 text-white':'rounded-bl-md border border-white/[.06] bg-white/[.035] text-zinc-300'}`}>{m.content}{m.role==='assistant'&&<button onClick={()=>navigator.clipboard.writeText(m.content)} className="mt-3 flex items-center gap-1 text-[8px] uppercase tracking-wider text-violet-300"><i className="ti ti-copy"/>Copiar respuesta</button>}</div></div>)}
     {chat.isPending&&<div className="flex justify-start"><div className="flex items-center gap-2 rounded-2xl rounded-bl-md border border-white/[.06] bg-white/[.035] px-4 py-3"><span className="h-1.5 w-1.5 animate-bounce rounded-full bg-violet-400"/><span className="h-1.5 w-1.5 animate-bounce rounded-full bg-violet-400 [animation-delay:120ms]"/><span className="h-1.5 w-1.5 animate-bounce rounded-full bg-violet-400 [animation-delay:240ms]"/></div></div>}
     {chat.error&&<p className="rounded-xl bg-rose-400/[.07] p-3 text-[9px] leading-4 text-rose-300">{(chat.error as Error).message}</p>}
    </div>
    <div className="relative border-t border-white/[.055] p-4">
     <div className="mb-3 flex gap-2 overflow-x-auto pb-1">{['¿Qué le respondo?','¿Cuándo hago seguimiento?','Dame una estrategia de cierre'].map(q=><button key={q} onClick={()=>sendChat(q)} disabled={!draft.leadId||chat.isPending} className="shrink-0 rounded-full border border-white/[.07] bg-white/[.025] px-3 py-1.5 text-[8px] text-zinc-400 transition hover:border-violet-400/20 hover:text-violet-200">{q}</button>)}</div>
     <form onSubmit={e=>{e.preventDefault();sendChat()}} className="flex items-end gap-2 rounded-2xl border border-white/[.075] bg-black/25 p-2 focus-within:border-violet-400/25">
      <textarea value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}}} rows={2} placeholder="Pegá el mensaje del cliente o preguntame qué hacer…" className="min-h-[48px] flex-1 resize-none border-0 bg-transparent px-2 py-2 text-[10px] leading-4 text-white outline-none placeholder:text-zinc-700"/>
      <button type="submit" disabled={!chatInput.trim()||!draft.leadId||chat.isPending} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-indigo-600 text-white shadow-lg shadow-violet-950/30 disabled:opacity-30"><i className="ti ti-arrow-up"/></button>
     </form>
     <button onClick={()=>coach.mutate()} disabled={!draft.leadId||coach.isPending} className="mt-3 w-full text-center text-[8px] uppercase tracking-[.16em] text-zinc-600 transition hover:text-violet-300">{coach.isPending?'Analizando…':'Generar diagnóstico estructurado'}</button>
     {coach.error&&<p className="mt-2 rounded-xl bg-rose-400/[.07] p-2 text-[9px] text-rose-300">{(coach.error as Error).message}</p>}
     {advice&&<div className="mt-3 rounded-2xl border border-cyan-300/10 bg-cyan-300/[.035] p-3"><div className="flex items-center justify-between"><p className="future-label">Diagnóstico · {advice.score}/100</p><button onClick={copy} className="text-[8px] text-violet-300">{copied?'Copiado':'Copiar mensaje'}</button></div><p className="mt-2 text-[10px] leading-4 text-cyan-100">{advice.nextStep}</p></div>}
    </div>
   </aside>
  </section>
 </div></main>
 <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="Agregar taller" subtitle="Creá una nueva oportunidad de adquisición"><form onSubmit={e=>{e.preventDefault();save.mutate(draft)}} className="space-y-4"><Field label="Nombre del taller *"><Input required value={draft.companyName} onChange={e=>set('companyName',e.target.value)} placeholder="Ej: WR Performance"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Contacto"><Input value={draft.contactName} onChange={e=>set('contactName',e.target.value)}/></Field><Field label="País"><Input value={draft.country} onChange={e=>set('country',e.target.value)}/></Field></div><Field label="Instagram"><Input value={draft.instagram} onChange={e=>set('instagram',e.target.value)} placeholder="@taller"/></Field><Field label="WhatsApp"><Input value={draft.whatsapp} onChange={e=>set('whatsapp',e.target.value)}/></Field><Field label="Observación inicial"><textarea value={draft.observation} onChange={e=>set('observation',e.target.value)} rows={3} className="w-full" placeholder="Qué viste y por qué es un buen prospecto…"/></Field><button type="submit" disabled={save.isPending} className="w-full rounded-full bg-[var(--accent)] py-3 text-xs font-semibold text-white">{save.isPending?'Creando…':'Crear oportunidad'}</button></form></Modal>
 </>
}
